-- date:   October 17, 21:36 (UTC-5)
-- author: Fernando Vazquez

DROP DATABASE IF EXISTS NETFLIX_CLONE;
CREATE DATABASE IF NOT EXISTS NETFLIX_CLONE;

DROP TABLE IF EXISTS ACTORS;
CREATE TABLE IF NOT EXISTS ACTORS (
    ID_ACTOR INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ACTORS PRIMARY KEY (ID_ACTOR),
    NAME TEXT NULL
);

DROP TABLE IF EXISTS DIRECTORS;
CREATE TABLE IF NOT EXISTS DIRECTORS (
    ID_DIRECTOR INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_DIRECTORS PRIMARY KEY (ID_DIRECTOR),
    NAME TEXT NULL
);

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID_CATEGORIE INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID_CATEGORIE),
    NAME TEXT NULL
);

DROP TABLE IF EXISTS MOVIES;
CREATE TABLE IF NOT EXISTS MOVIES (
    ID_MOVIE INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_MOVIES PRIMARY KEY (ID_MOVIE),
    NAME TEXT NULL,
    CREATED_AT DATETIME NULL,
    UPDATED_AT DATETIME NULL,
    DELETED_AT DATETIME NULL,
    BACKGROUND_URL TEXT NULL,
    DURATION TEXT NULL,
    YEAR_RELEASED INT(4) NULL,
    DESCRIPTION TEXT NULL,
    VIDEO_URL TEXT NULL
);

DROP TABLE IF EXISTS MOVIES_has_ACTORS;
CREATE TABLE IF NOT EXISTS MOVIES_has_ACTORS (
    ID_MHA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_MHA PRIMARY KEY (ID_MHA),
    ID_MOVIE INT NOT NULL,
    CONSTRAINT FK_MOVIES_has_ACTORS_TO_ACTORS FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES (ID_MOVIE),
    ID_ACTOR INT NOT NULL,
    CONSTRAINT FK_MOVIES_has_ACTORS_TO_ACTORS FOREIGN KEY (ID_ACTOR) REFERENCES ACTORS (ID_ACTOR)
);

DROP TABLE IF EXISTS MOVIES_has_DIRECTORS;
CREATE TABLE IF NOT EXISTS MOVIES_has_DIRECTORS (
    ID_MHS INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_MHS PRIMARY KEY (ID_MHS),
    ID_MOVIE INT NOT NULL,
    CONSTRAINT FK_MOVIES_has_DIRECTORS_TO_MOVIES FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES (ID_MOVIE),
    ID_DIRECTOR INT NOT NULL,
    CONSTRAINT FK_MOVIES_has_DIRECTORS_TO_DIRECTORS FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTORS (ID_DIRECTOR)
);

DROP TABLE IF EXISTS MOVIES_has_CATEGORIES;
CREATE TABLE IF NOT EXISTS MOVIES_has_CATEGORIES (
    ID_MHC INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_MHC PRIMARY KEY (ID_MHC),
    ID_MOVIE INT NOT NULL,
    CONSTRAINT FK_MOVIES_has_CATEGORIES_TO_MOVIES FOREIGN KEY (ID_MOVIE) REFERENCES MOVIES (ID_MOVIE),
    ID_CATEGORY INT NOT NULL,
    CONSTRAINT FK_MOVIES_has_CATEGORIES_TO_CATEGORIES FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY)
);

DROP TABLE IF EXISTS SERIES;
CREATE TABLE IF NOT EXISTS SERIES (
    ID_SERIE INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_SERIES PRIMARY KEY (ID_SERIE),
    NAME TEXT NULL,
    BACKGROUND_URL TEXT NULL,
    CREATED_AT DATETIME NULL,
    UPDATED_AT DATETIME NULL,
    DELETED_AT DATETIME NULL,
    YEAR_RELEASED INT(4) NULL,
    NUMBER_OF_SEASONS INT NULL,
    DESCRIPTION TEXT NULL
);

DROP TABLE IF EXISTS SERIES_has_ACTORS;
CREATE TABLE IF NOT EXISTS SERIES_has_ACTORS (
    ID_SHA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_SHA PRIMARY KEY (ID_SHA),
    ID_SERIE INT NOT NULL,
    CONSTRAINT FK_SERIES_has_ACTORS_TO_SERIES FOREIGN KEY (ID_SERIE) REFERENCES SERIES (ID_SERIE),
    ID_ACTOR INT NOT NULL,
    CONSTRAINT FK_SERIES_has_ACTORS_TO_ACTORS FOREIGN KEY (ID_ACTOR) REFERENCES ACTORS (ID_ACTOR)
);

DROP TABLE IF EXISTS SERIES_has_DIRECTORS;
CREATE TABLE IF NOT EXISTS SERIES_has_DIRECTORS (
    ID_SHD INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_SHD PRIMARY KEY (ID_SHD),
    ID_SERIE INT NOT NULL,
    CONSTRAINT FK_SERIES_has_DIRECTORS_TO_SERIES FOREIGN KEY (ID_SERIE) REFERENCES SERIES (ID_SERIE),
    ID_DIRECTOR INT NOT NULL,
    CONSTRAINT FK_SERIES_has_DIRECTORS_TO_DIRECTORS FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTORS (ID_DIRECTOR)
);

DROP TABLE IF EXISTS SERIES_has_CATEGORIES;
CREATE TABLE IF NOT EXISTS SERIES_has_CATEGORIES (
    ID_SHC INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_SHC PRIMARY KEY (ID_SHC),
    ID_SERIE INT NOT NULL,
    CONSTRAINT FK_SERIES_has_CATEGORIES_TO_SERIES FOREIGN KEY (ID_SERIE) REFERENCES SERIES (ID_SERIE),
    ID_CATEGORY INT NOT NULL,
    CONSTRAINT FK_SERIES_has_CATEGORIES_TO_CATEGORIES FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES (ID_CATEGORY)
);
