CREATE DATABASE IF NOT EXISTS NETFLIX_CLONE;

USE NETFLIX_CLONE;

CREATE TABLE IF NOT EXISTS TYPES (
    ID_TYPE INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_TYPES PRIMARY KEY (ID_TYPE),
    NAME TEXT NULL
);

CREATE TABLE IF NOT EXISTS PLANS (
    ID_PLAN INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_PLANS PRIMARY KEY (ID_PLAN),
    NAME TEXT NULL,
    PRICE FLOAT NULL
);

CREATE TABLE IF NOT EXISTS ACTORS (
    ID_ACTOR INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ACTORS PRIMARY KEY (ID_ACTOR),
    UUID TEXT NULL,
    NAME TEXT NULL,
    LASTNAME TEXT NULL,
    EMAIL TEXT NULL,
    PASS TEXT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID_CATEGORY INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID_CATEGORY),
    NAME TEXT NULL
);

CREATE TABLE IF NOT EXISTS ICONS (
    ID_ICON INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ICONS PRIMARY KEY (ID_ICON),
    SOURCE TEXT NULL
);

CREATE TABLE IF NOT EXISTS BACKGROUNDS (
    ID_BACKGROUND INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_BACKGROUNDS PRIMARY KEY (ID_BACKGROUND),
    SOURCE TEXT NULL
);
